In [1]:
import numpy as np


def gaussian_elimination(A, b):
   #Initial matrix
   n = A.shape[0]
   print(f"n={n}")
   # Merge A with B to test matrix
   test_matrix=np.concatenate((A, np.reshape(b, (n, 1))), axis=1)
   #Initial A inverse to lower_triangular
   lower_triangular=np.eye(n,n)
   print(f"Initial augmented m0atrix: \n{test_matrix}")
   print(f"Initial A inverse matrix \n{lower_triangular}")
   #elimination to upper_triangular matrix
   E_matrix, A_inv=forward_elimination(n,test_matrix, lower_triangular)
   #determine the after elimination matrix  is singular or not
   if is_singular(E_matrix[:,:n]):
       print(f"It is singular")
       #check if it has no solution or infinity solutions
       if np.linalg.matrix_rank(E_matrix[:,:n])> np.linalg.matrix_rank(E_matrix):
           print(f"There is no solution")
       else:
           print("There are infinity solutions")
   else:
        Back_substitution(n,test_matrix)



def forward_elimination(n, test_matrix, A_inv):
   for k in range(n-1):
       #determine pivot=>row and column index=k
       pivot = test_matrix[k, k]
       # if pivot ==0 stop and continue
       if pivot == 0:
           continue
       #for i=k+1 to n
       for i in range(k+1, n):
           factor = test_matrix[i, k] / pivot
           test_matrix[i, k:] -= factor * test_matrix[k, k:]
           A_inv[i,k]=factor
           print(f"\n Elimination cell location(column, row){k+1,i+1}:")
           print(f"\n test_matrix \n{test_matrix}")
           print(f"\n A Inverse \n{A_inv}")
   return test_matrix,A_inv


def Back_substitution(n,test_matrix):
   # Upper_triangular:Back substitution
   x = np.zeros(n)
   #for j in range to 1, index is from 3-0
   for j in range(n-1, -1, -1):
       # find the x value, initial pivot
       pivot = test_matrix[j, j]
       # if u[j,j]=0, stop and continue
       if pivot == 0:
           continue
       # get x from the x=bi-m[j,-1]/u[j,]
       x[j] = test_matrix[j, -1] / pivot
       #for i=j-1 to 0
       for i in range(j-1, -1, -1):
           test_matrix[i, -1] -= test_matrix[i, j] * x[j]
   #print x value
   for k in range(0,n):
       print(f"\nx{k+1}= {x[k]}")

   return x
#To determine if the linear algebra is singular
def is_singular(matrix):
   determinant = np.linalg.det(matrix)
   return determinant == False


# Given matrices
A = np.array([[1, 2, 1, -1],
             [3, 2, 4, 4],
             [4, 4, 3, 4],
             [2, 0, 1, 5]], dtype=float)
b = np.array([5, 16, 22, 15], dtype=float)


x = gaussian_elimination(A, b)






n=4
Initial augmented m0atrix: 
[[ 1.  2.  1. -1.  5.]
 [ 3.  2.  4.  4. 16.]
 [ 4.  4.  3.  4. 22.]
 [ 2.  0.  1.  5. 15.]]
Initial A inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Elimination cell location(column, row)(1, 2):

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 4.  4.  3.  4. 22.]
 [ 2.  0.  1.  5. 15.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Elimination cell location(column, row)(1, 3):

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 0. -4. -1.  8.  2.]
 [ 2.  0.  1.  5. 15.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [4. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Elimination cell location(column, row)(1, 4):

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 0. -4. -1.  8.  2.]
 [ 0. -4. -1.  7.  5.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [4. 0. 1. 0.]
 [2. 0. 0. 1.]]

 Elimination cell location(column, row)(2, 3):

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1

In [5]:
# Given matrices
A = np.array([[1, 2, 1, -1],
              [3, 2, 4, 4],
              [4, 4, 3, 4],
              [2, 0, 1, 5]], dtype=float)
b = np.array([5, 16, 22, 15], dtype=float)

x = gaussian_elimination(A, b)

n=4
Initial augmented matrix: 
[[ 1.  2.  1. -1.  5.]
 [ 3.  2.  4.  4. 16.]
 [ 4.  4.  3.  4. 22.]
 [ 2.  0.  1.  5. 15.]]
Initial A inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

After elimination step 1:

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 4.  4.  3.  4. 22.]
 [ 2.  0.  1.  5. 15.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

After elimination step 1:

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 0. -4. -1.  8.  2.]
 [ 2.  0.  1.  5. 15.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [4. 0. 1. 0.]
 [0. 0. 0. 1.]]

After elimination step 1:

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 0. -4. -1.  8.  2.]
 [ 0. -4. -1.  7.  5.]]

 A Inverse 
[[1. 0. 0. 0.]
 [3. 1. 0. 0.]
 [4. 0. 1. 0.]
 [2. 0. 0. 1.]]

After elimination step 2:

 test_matrix 
[[ 1.  2.  1. -1.  5.]
 [ 0. -4.  1.  7.  1.]
 [ 0.  0. -2.  1.  1.]
 [ 0. -4. -1.  7.  5.]]

 A Inverse 
[[1. 0. 0. 0.]