In [3]:
'''QR factory by using householder transformation to get Q,R.
Because Rx=C, use back substitution to get x_head.
x_delt=x_true-x_head'''

import numpy as np

def householder_transformation(arr):

    #get row size form matrix
    arr_size = arr.size
    #get e1=[1,0,0,0,0]
    e1 = np.zeros_like(arr)
    e1[0] = 1
    #calculate vector: v_alfa= sign(arr)( norm(arr,2)*e1)
    vector = np.linalg.norm(arr,2) * e1

    if arr[0] < 0:
        #if the arr[0] is negative, change the sign to negative
        vector = - vector
    #get vector transpose, when arr input as shape=(1,arr_size), which is the same shape as vector Transpose
    v_T = arr + vector
    #get vector, reshape the v_T
    v=v_T.reshape(arr.size,1)
    #H=I-2 * (v @ v.T)/ (v.T @ v)
    I=np.identity(arr_size)
    calculation_v=2 * (v @ v.T)/ (v.T @ v)
    H = I - calculation_v

    return H

def QR_factorized(q, r, i, row):
    """
    Return Q and R matrices
    """
    v = np.array(r[i:, i]).T
    H_head = householder_transformation(v)
    # H=I, it keeps unchange.
    H = np.eye(row)
    #include for Hhead=H[i:,j:],plug in the transform parts
    H[i:, i:] = H_head
    R = np.dot(H, r)
    Q = np.dot(q, H)
    return Q, R

def Back_substitution(n,test_matrix):
   # Upper_triangular:Back substitution
   x = np.zeros(n)
   #for j in range to 1, index is from 3-0
   for j in range(n-1, -1, -1):
       # find the x value, initial pivot
       pivot = test_matrix[j, j]
       # if u[j,j]=0, stop and continue
       if pivot == 0:
           continue
       # get x from the x=bi-m[j,-1]/u[j,]
       x[j] = test_matrix[j, -1] / pivot
       #for i=j-1 to 0
       for i in range(j-1, -1, -1):
           test_matrix[i, -1] -= test_matrix[i, j] * x[j]
   #print x value
   #for k in range(0,n):
       #print(f"\nx{k+1}= {x[k]}")

   return x

A = np.array([[1, 0, 0, 0],
             [0, 1, 0, 0],
             [0, 0, 1, 0],
             [0, 0, 0, 1],
            [1, -1, 0, 0],
            [1, 0, -1, 0],
            [1, 0, 0, -1],
            [0, 1, -1, 0],
            [0, 1, 0, -1],
            [0, 0, 1, -1]])

B= np.array([2.95,1.74,-1.45,1.32,1.23,4.45,1.61,3.21,0.45,-2.75])

X= np.array([2.95,1.74,-1.45,1.32])
test_matrix=np.concatenate((A, np.reshape(B, (np.size(B), 1))), axis=1)

column = int(np.size(A, 1))
row = np.size(A, 0)
print('Matrix \n', test_matrix)
Q = np.identity(row)
R = test_matrix
for i in range(column):
    # For each iteration, H matrix is calculated for (i+1)th row
    Q, R = QR_factorized(Q, R, i, row)

R = np.around(R, decimals=2)


#get R shape is same as Matrix transpose
R_Matrix = R[:column, :-1]
C = R[:column,-1]
Q = np.around(Q, decimals=2)

print('After QR factorization')
print('R matrix')
print(R, '\n')
print('Q matrix')
print(Q,'\n')
print(f'Q X R=A\n{np.around(np.matmul(Q,R),decimals=2)}\n')
print('C matrix')
print(C,'\n')

x_true=np.array([2.95,1.74,-1.45,1.32])
n=R_Matrix.shape[0]
x_head=np.around(Back_substitution(n,R),decimals=4)
x_delta= np.subtract(x_head,x_true)

print(f'x_true\tx_head\t\t\tx_delta')
for i,j,k in zip(x_true , x_head, x_delta):
    print(f'{i}\t{j:>4}\t\t\t{k:.4f}')

Matrix 
 [[ 1.    0.    0.    0.    2.95]
 [ 0.    1.    0.    0.    1.74]
 [ 0.    0.    1.    0.   -1.45]
 [ 0.    0.    0.    1.    1.32]
 [ 1.   -1.    0.    0.    1.23]
 [ 1.    0.   -1.    0.    4.45]
 [ 1.    0.    0.   -1.    1.61]
 [ 0.    1.   -1.    0.    3.21]
 [ 0.    1.    0.   -1.    0.45]
 [ 0.    0.    1.   -1.   -2.75]]
After QR factorization
R matrix
[[-2.    0.5   0.5   0.5  -5.12]
 [ 0.   -1.94  0.65  0.65 -3.48]
 [ 0.    0.   -1.83  0.91  3.87]
 [ 0.    0.    0.   -1.58 -2.08]
 [ 0.   -0.   -0.   -0.    0.02]
 [ 0.    0.   -0.   -0.    0.04]
 [ 0.    0.    0.   -0.   -0.03]
 [-0.    0.   -0.   -0.    0.01]
 [-0.    0.    0.   -0.    0.02]
 [-0.   -0.   -0.   -0.    0.02]] 

Q matrix
[[-0.5  -0.13 -0.18 -0.32 -0.46 -0.45 -0.43  0.01  0.03  0.02]
 [ 0.   -0.52 -0.18 -0.32  0.43 -0.03 -0.01 -0.46 -0.44  0.02]
 [ 0.    0.   -0.55 -0.32  0.01  0.44 -0.02  0.43 -0.03 -0.46]
 [ 0.    0.    0.   -0.63  0.01  0.03  0.46  0.02  0.45  0.43]
 [-0.5   0.39 -0.   -0.    0.72 -0

In [120]:

import numpy as np

def householder_transformation(arr):

    #get row size form matrix
    arr_size = arr.size
    #get e1=[1,0,0,0,0]
    e1 = np.zeros_like(arr)
    e1[0] = 1
    #calculate vector: v_alfa= sign(arr)( norm(arr,2)*e1)
    vector = -np.linalg.norm(arr,2) * e1

    if arr[0] < 0:
        #if the arr[0] is negative, change the sign to negative
        vector = - vector
    #get vector transpose, when arr input as shape=(1,arr_size), which is the same shape as vector Transpose
    v_T = arr - vector
    print(v_T)
    #get vector, reshape the v_T
    v=v_T.reshape(arr.size,1)
    #H=I-2 * (v @ v.T)/ (v.T @ v)
    I=np.identity(arr_size)
    calculation_v=2 * (v @ v.T)/ (v.T @ v)
    H = I - calculation_v

    return H

def QR_factorized(q, r, i, row):
    """
    Return Q and R matrices
    """
    #a[k]
    arr = np.array(r[i:, i]).T
    H_head = householder_transformation(arr)
    # H=I, it keeps unchange.
    H = np.eye(row)
    #include for Hhead=H[i:,j:],plug in the transform parts
    H[i:, i:] = H_head
    R = np.dot(H, r)
    Q = np.dot(q, H)
    return Q, R

A = np.array([[1, -1, 4],
            [1, 4,-2],
            [1, 4, 2],
            [1, -1, 0]])
column = int(np.size(A, 1))
row = np.size(A, 0)
print(row)
print('Matrix \n', A)
Q = np.identity(row)
R = A
n=0
for i in range(column):
    # For each iteration, H matrix is calculated for (i+1)th row
    Q, R = QR_factorized(Q, R, i, row)
    R = np.around(R, decimals=6)
    Q = np.around(Q, decimals=6)
    n+=1
    print(f'{n} time: \n Q{n}={Q}, \n R{n}={R}')

#get R shape is same as Matrix transpose
R_Matrix = R[:column, :-1]
C = R[:column,-1]


print('\nFinal Result:')
print('R matrix')
print(R, '\n')
print('Q matrix')
print(Q,'\n')
print(f'Q X R=A\n{np.around(np.matmul(Q,R),decimals=2)}\n')
print('C1 matrix')
print(C,'\n')


4
Matrix 
 [[ 1 -1  4]
 [ 1  4 -2]
 [ 1  4  2]
 [ 1 -1  0]]
[3. 1. 1. 1.]
1 time: 
 Q1=[[-0.5      -0.5      -0.5      -0.5     ]
 [-0.5       0.833333 -0.166667 -0.166667]
 [-0.5      -0.166667  0.833333 -0.166667]
 [-0.5      -0.166667 -0.166667  0.833333]], 
 R1=[[-2.       -3.       -2.      ]
 [ 0.        3.333333 -4.      ]
 [ 0.        3.333333  0.      ]
 [ 0.       -1.666667 -2.      ]]
[ 8.33333267  3.333333   -1.666667  ]
2 time: 
 Q2=[[-0.5       0.5      -0.1      -0.7     ]
 [-0.5      -0.5      -0.7       0.1     ]
 [-0.5      -0.5       0.7      -0.1     ]
 [-0.5       0.5       0.1       0.699999]], 
 R2=[[-2.  -3.  -2. ]
 [ 0.  -5.   2. ]
 [ 0.   0.   2.4]
 [ 0.  -0.  -3.2]]
[ 6.4 -3.2]
3 time: 
 Q3=[[-0.5       0.5      -0.5      -0.5     ]
 [-0.5      -0.5       0.5      -0.5     ]
 [-0.5      -0.5      -0.5       0.5     ]
 [-0.5       0.5       0.499999  0.499999]], 
 R3=[[-2. -3. -2.]
 [ 0. -5.  2.]
 [ 0.  0. -4.]
 [ 0.  0. -0.]]

Final Result:
R matrix
[[-2. -3.

In [150]:


import numpy as np

def householder_transformation(H,matrix):
    #get column size form matrix
    column = np.shape(matrix)[1]
    print(column)
    R=matrix.copy() # matrix transpose to obtain a[k]
    q=H.copy()
    v=np.zeros_like(R)
    for k in range(column):
        print(f'when k=\t{k}:')
        #get e1=[1,0,0,0]
        arr=R[k:,k].astype(float)
        arr_size = arr.size
#Option:define vector function to calculate and return vector
         # obtain e=[1,0,0,0] as array like if k=0
        vector=arr
        #calculate vector: v_alfa= - sign(arr)( norm(arr,2)*e), if arr[0]>0
        if arr[0] <0:
            vector= np.linalg.norm(arr,2) * H[k:,k]
        else:
            vector=-np.linalg.norm(arr,2) * H[k:,k]
        print(f'vector=\t{vector}')
        # get beta=V_transpose*v
        #get vector transpose, when arr input as shape=(1,arr_size), which is the same shape as vector Transpose
        v[k:,k] =np.around(R[k:,k].T  - vector,decimals=0)
        print(f'v=\n{v}')
        #get vector, reshape the v_T

        #H=a[j]-2 * (v_T*a[j])/ (v.T @ v)
        beta=np.around(v[k:,k].T@v[k:,k],decimals=0)
        print(f'beta{beta}')
        if beta == 0:
            continue
#Option: define a function to calculate and return R
        for j in range(k,column):
            #get gamma(j)=v_transpose*a(j)
            print(f'H{k}a{j}:')

            gamma=np.around(v[k:,k].T@R[k:,j],decimals=0)
            print(f'gamma=\t{gamma}')
            calculation_v=np.around(((2 * gamma)/ beta)*v[k:,k],decimals=0)
            print(f'calculation_v=2 * (v_T*a[j])/ (v.T @ v)= \t{calculation_v}')
            R=R.astype(float)
            R[k:,j]=R[k:,j]-calculation_v

            print(f'R=\n{R}')

    return R

A = np.array([[1, -1, 4],
            [1, 4,-2],
            [1, 4, 2],
            [1, -1, 0]])
column = int(np.size(A, 1))
row = np.size(A, 0)

print('Matrix \n', A)
H = np.identity(row)
R = householder_transformation(H, A)






Matrix 
 [[ 1 -1  4]
 [ 1  4 -2]
 [ 1  4  2]
 [ 1 -1  0]]
3
when k=	0:
vector=	[-2. -0. -0. -0.]
v=
[[3 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
beta12
H0a0:
gamma=	6
calculation_v=2 * (v_T*a[j])/ (v.T @ v)= 	[3. 1. 1. 1.]
R=
[[-2. -1.  4.]
 [ 0.  4. -2.]
 [ 0.  4.  2.]
 [ 0. -1.  0.]]
H0a1:
gamma=	4.0
calculation_v=2 * (v_T*a[j])/ (v.T @ v)= 	[2. 1. 1. 1.]
R=
[[-2. -3.  4.]
 [ 0.  3. -2.]
 [ 0.  3.  2.]
 [ 0. -2.  0.]]
H0a2:
gamma=	12.0
calculation_v=2 * (v_T*a[j])/ (v.T @ v)= 	[6. 2. 2. 2.]
R=
[[-2. -3. -2.]
 [ 0.  3. -4.]
 [ 0.  3.  0.]
 [ 0. -2. -2.]]
when k=	1:
vector=	[-4.69041576 -0.         -0.        ]
v=
[[ 3  0  0]
 [ 1  8  0]
 [ 1  3  0]
 [ 1 -2  0]]
beta77
H1a1:
gamma=	37.0
calculation_v=2 * (v_T*a[j])/ (v.T @ v)= 	[ 8.  3. -2.]
R=
[[-2. -3. -2.]
 [ 0. -5. -4.]
 [ 0.  0.  0.]
 [ 0.  0. -2.]]
H1a2:
gamma=	-28.0
calculation_v=2 * (v_T*a[j])/ (v.T @ v)= 	[-6. -2.  1.]
R=
[[-2. -3. -2.]
 [ 0. -5.  2.]
 [ 0.  0.  2.]
 [ 0.  0. -3.]]
when k=	2:
vector=	[-3.60555128 -0.        ]
v=
[[ 3 

In [25]:
'''ChatGPT version'''

import numpy as np

def householder_transformation(matrix):
    m, n = matrix.shape
    Q = np.identity(m)
    R = matrix.copy()

    for j in range(n):
        x = R[j:, j]
        norm_x = np.linalg.norm(x)
        v = x.copy()
        v[0] += np.copysign(norm_x, x[0])
        v /= np.linalg.norm(v)

        R[j:, :] -= 2.0 * np.outer(v, np.dot(v, R[j:, :]))
        Q[:, j:] -= 2.0 * np.outer(np.dot(Q[:, j:], v), v)

    return Q, R

A = np.array([[1, -1, 4],
              [1, 4, -2],
              [1, 4, 2],
              [1, -1, 0]])

Q, R = householder_transformation(A.astype(float))

R = np.around(R, decimals=6)
Q = np.around(Q, decimals=6)

print('Q matrix:')
print(Q)
print('\nR matrix:')
print(R)


Q matrix:
[[-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5  0.5  0.5]]

R matrix:
[[-2. -3. -2.]
 [ 0. -5.  2.]
 [-0.  0. -4.]
 [-0.  0.  0.]]
