In [2]:
'''QR factory by using householder transformation to get Q,R.
Because Rx=C, use back substitution to get x_head.
x_delt=x_true-x_head'''

import numpy as np

def householder_transformation(arr):

    #get row size form matrix
    arr_size = arr.size
    #get e1=[1,0,0,0,0]
    e1 = np.zeros_like(arr)
    e1[0] = 1
    #calculate vector: v_alfa= sign(arr)( norm(arr,2)*e1)
    vector = np.linalg.norm(arr,2) * e1

    if arr[0] < 0:
        #if the arr[0] is negative, change the sign to negative
        vector = - vector
    #get vector transpose, when arr input as shape=(1,arr_size), which is the same shape as vector Transpose
    v_T = arr + vector
    #get vector, reshape the v_T
    v=v_T.reshape(arr.size,1)
    #H=I-2 * (v @ v.T)/ (v.T @ v)
    I=np.identity(arr_size)
    calculation_v=2 * (v @ v.T)/ (v.T @ v)
    H = I - calculation_v

    return H

def QR_factorized(q, r, i, row):
    """
    Return Q and R matrices
    """
    v = np.array(r[i:, i]).T
    H_head = householder_transformation(v)
    # H=I, it keeps unchange.
    H = np.eye(row)
    #include for Hhead=H[i:,j:],plug in the transform parts
    H[i:, i:] = H_head
    R = np.dot(H, r)
    Q = np.dot(q, H)
    return Q, R

def Back_substitution(n,test_matrix):
   # Upper_triangular:Back substitution
   x = np.zeros(n)
   #for j in range to 1, index is from 3-0
   for j in range(n-1, -1, -1):
       # find the x value, initial pivot
       pivot = test_matrix[j, j]
       # if u[j,j]=0, stop and continue
       if pivot == 0:
           continue
       # get x from the x=bi-m[j,-1]/u[j,]
       x[j] = test_matrix[j, -1] / pivot
       #for i=j-1 to 0
       for i in range(j-1, -1, -1):
           test_matrix[i, -1] -= test_matrix[i, j] * x[j]
   #print x value
   #for k in range(0,n):
       #print(f"\nx{k+1}= {x[k]}")

   return x

A = np.array([[1, -1, 0, 0],
            [1, 0, -1, 0],
            [1, 0, 0, -1],
            [0, 1, -1, 0],
            [0, 1, 0, -1],
            [0, 0, 1, -1]])

B= np.array([1.23,4.45,1.61,3.21,0.45,-2.75])

X= np.array([2.95,1.74,-1.45,1.32])
test_matrix=np.concatenate((A, np.reshape(B, (np.size(B), 1))), axis=1)

column = int(np.size(A, 1))
row = np.size(A, 0)
print('Matrix \n', test_matrix)
Q = np.identity(row)
R = test_matrix
for i in range(column):
    # For each iteration, H matrix is calculated for (i+1)th row
    Q, R = QR_factorized(Q, R, i, row)

R = np.around(R, decimals=6)


#get R shape is same as Matrix transpose
R_Matrix = R[:column, :-1]
C = R[:column,-1]
Q = np.around(Q, decimals=6)

print('After QR factorization')
print('R matrix')
print(R, '\n')
print('Q matrix')
print(Q,'\n')
print(f'Q X R=A\n{np.around(np.matmul(Q,R),decimals=2)}\n')
print('C matrix')
print(C,'\n')

x_true=np.array([2.95,1.74,-1.45,1.32])
n=R_Matrix.shape[0]
x_head=np.around(Back_substitution(n,R),decimals=4)
x_delta= np.subtract(x_head,x_true)

print(f'x_true\tx_head\t\t\tx_delta')
for i,j,k in zip(x_true , x_head, x_delta):
    print(f'{i}\t{j:>4}\t\t\t{k:.4f}')



Matrix 
 [[ 1.   -1.    0.    0.    1.23]
 [ 1.    0.   -1.    0.    4.45]
 [ 1.    0.    0.   -1.    1.61]
 [ 0.    1.   -1.    0.    3.21]
 [ 0.    1.    0.   -1.    0.45]
 [ 0.    0.    1.   -1.   -2.75]]
After QR factorization
R matrix
[[-1.732051  0.57735   0.57735   0.57735  -4.208883]
 [ 0.       -1.632993  0.816497  0.816497 -2.97613 ]
 [-0.        0.       -1.414214  1.414214  3.924443]
 [-0.        0.        0.       -0.        0.046981]
 [ 0.       -0.        0.        0.        0.014197]
 [ 0.       -0.        0.        0.        0.029854]] 

Q matrix
[[-0.57735   0.408248 -0.       -0.066592  0.634133  0.305681]
 [-0.57735  -0.204124  0.353553  0.61742  -0.343431  0.029103]
 [-0.57735  -0.204124 -0.353553 -0.550829 -0.290702 -0.334784]
 [ 0.       -0.612372  0.353553 -0.392585  0.071626  0.583735]
 [ 0.       -0.612372 -0.353553  0.325993  0.562507 -0.278055]
 [ 0.        0.       -0.707107  0.224836 -0.271805  0.612838]] 

Q X R=A
[[ 1.   -1.    0.    0.    1.23]
 [ 1.   